version: "3.9"
services:
  redis:
    image: redis:7.0.4
    volumes:
      - redis:/data

  db:
    image: postgres:14.5
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  client:
    build: client
    image: node:18.9.0
    volumes:
      - ./client:/src
    command: /bin/bash -c "cd /src/ && npm install && npm run dev"
    ports:
      - "5173:5173"

  web:
    build: .
    image: imdb
    links:
      - db:db
      - redis:redis
    volumes:
      - .:/src
      - ./static:/static
    env_file:
      - envs/db.env
      - envs/.env
    command: /bin/bash -c 'pip install -r requirements.txt && invoke run'
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker

  celery:
    build: .
    image: imdb
    links:
      - db:db
      - redis:redis
    volumes:
      - .:/src
    env_file:
      - envs/db.env
      - envs/.env
    command: /bin/bash -c 'pip install -r requirements.txt && celery -A config.celery.app worker'


  nginx:
    image: nginx:1.23.1
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
    links:
      - web:web
    ports:
      - "8000:80"

volumes:
  pgdata: {}
  static: {}
  redis: {}
