# Generated by Django 4.1.1 on 2022-09-16 09:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, verbose_name='IMDB ID')),
                ('title_type', models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], max_length=255, verbose_name='Title Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_adult', models.BooleanField(verbose_name='Is Adult')),
                ('year', models.IntegerField(null=True, verbose_name='Release Year')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, verbose_name='IMDB ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_year', models.IntegerField(null=True, verbose_name='Birth Year')),
                ('death_year', models.IntegerField(null=True, verbose_name='Death Year')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(verbose_name='Ordering')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('job', models.CharField(max_length=255, null=True, verbose_name='Job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='Characters')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb.movie', verbose_name='Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb.person', verbose_name='Person')),
            ],
        ),
    ]
