# Generated by Django 4.1.1 on 2022-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(verbose_name='Adult'),
        ),
    ]
